### ISSUE TITLE
Error on Case Expression

### ISSUE THREAD

**Issue by Diama1** [Diama1/Elm-levelUp#1]
![Screen Shot 2020-08-10 at 17 56 37](https://user-images.githubusercontent.com/32199791/89807565-1af36900-db39-11ea-8162-a6b45ff510fb.png)
here is the screenshot of the code but I am trying to use the case Expression with the anonymous and I am getting an error and I think the error was caused by the way maybe I wrote my types.
Here is the error 
![Screen Shot 2020-08-10 at 18 45 09](https://user-images.githubusercontent.com/32199791/89807983-b1278f00-db39-11ea-9920-ed8db43f4211.png)

@amitaibu

**Comment by amitaibu** [comment]
This part doesn't make sense - https://github.com/Diama1/Elm-levelUp/blob/047be75976361a26e9fed69428b8ec2a27ad9219/src/Main.elm#L19-L20

You would want the user to be part of the Model. Right now you made the Model as the auth's user info. You probably want something like this:

```elm
type alias Model =
    {user : User}

emptyModel : Model
emptyModel = 
    { user = Anonymous}
```

**Comment by amitaibu** [comment]
Or, if you wanted to start small you can say 

```elm
type alias Model =
    User

emptyModel : Model
emptyModel = 
   Anonymous
```

**Comment by Diama1** [comment]
Thank you, Now I understand what I was supposed to do. 
In addition to that, I managed to have the data displayed but in the case, I am having the one on anonymous 
![Screen Shot 2020-08-10 at 20 49 00](https://user-images.githubusercontent.com/32199791/89818970-f3a59780-db4a-11ea-98d8-d73c2d713380.png)

Here is the code
![Screen Shot 2020-08-10 at 20 50 38](https://user-images.githubusercontent.com/32199791/89819126-2e0f3480-db4b-11ea-896d-b5d02da491e0.png)

**Comment by Diama1** [comment]
I have a bug about ocClick event. I was trying to create an input field when the user is anonymous, but the issue is about submitting. the onClick even I am not understanding it very well. I would like you to help with that. I know that the onClick event needs a string but I am not getting it right. Here is the screenshot of the error and my codes.

![Screen Shot 2020-08-11 at 12 14 31](https://user-images.githubusercontent.com/32199791/89886629-3740e580-dbcd-11ea-900b-a09f3f0ce831.png)
 

![Screen Shot 2020-08-11 at 12 20 16](https://user-images.githubusercontent.com/32199791/89886621-3314c800-dbcd-11ea-9afe-86a14b66df7a.png)

@amitaibu

**Comment by amitaibu** [comment]
@Diama1 Thanks. please create a PR (Pull request) with the most up to date code, and there write the problem. So I could look at the code, and not the screenshot of it.

**Comment by Diama1** [comment]
@amitaibu I have pushed the latest changes. Maybe you can check them out.

**Comment by amitaibu** [comment]
Thanks. What's the current error that you get? Or what's the status?

**Comment by Diama1** [comment]
@amitaibu, As I was telling you, I tried to change the state from Anonymous to Authenticated but I am still confused on the onClick event once the user is anonymous and get a chance to enter the name. Maybe you can check the code and tell me what I am doing wrong.

**Comment by Diama1** [comment]
@amitaibu Here is how it looks by default
![Screen Shot 2020-08-11 at 14 46 25](https://user-images.githubusercontent.com/32199791/89898727-7ed16c80-dbe1-11ea-8671-636b1d80954f.png)

**Comment by amitaibu** [comment]
Please give me write access to the repo

**Comment by amitaibu** [comment]
I'll send an invite for tomorrow. Try to advance until then by reading the tutorial https://guide.elm-lang.org/

**Comment by Diama1** [comment]
I have sent you an invite on the repo.

**Comment by Diama1** [comment]
@amitaibu, I was trying to add the age form but I got this error. How do we set the **onInput** for **maybe Int**

![Screen Shot 2020-08-12 at 10 41 11](https://user-images.githubusercontent.com/32199791/89994519-8435c200-dc88-11ea-9c58-decef91f9a70.png)

**Comment by amitaibu** [comment]
@Diama1 Lets close this issue. Instead, please open a PR with the most up to date code, and have the error messages there.
